# Generated by Django 3.2.15 on 2022-12-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorvirtual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='autor',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
